export interface LoggedMeal {
  id: string;
  name: string;
  carbs: number;
  protein: number;
  fat: number;
  timestamp: Date;
  type: 'suggested' | 'custom' | 'manual' | 'api' | 'photo';
  transcript?: string; // To store what the user actually said
}

export interface ActivityLog {
  id: string;
  type: string;
  duration: number; // in minutes
  distance?: number; // in km
  heartRate?: number; // in bpm
  timestamp: Date;
}

export interface UserProfile {
  name: string;
  age: number;
  weight: number;
  targetCarbs: number;
  targetProtein: number;
  targetFat: number;
  dietaryRestrictions: string;
  foodPreferences: string;
}

export interface Exercise {
  id: string;
  name: string;
  sets: number;
  reps: string;
  description: string;
  imageUrl?: string; // Generated by AI
}

export interface TrainingDay {
  dayOfWeek: number; // 0 = Sunday, 1 = Monday, etc.
  focus: string; // e.g., "Piernas y Glúteos", "Descanso Activo"
  exercises: Exercise[];
}
